package org.knowtiphy.pinkpigmail.resources

/**
 * @author graham
 */
object Strings
{
    const val REPLY = "Reply to message"
    const val REPLY_ALL = "Reply all to message"
    const val FORWARD = "Forward message"
    const val SAVE_TO_DRAFTS = "Save a copy to drafts"
    const val SEND = "Send message"
    const val DELETE = "Delete message(s)"
    const val DELETE_FOREVER = "This action will delete the email forever. Are you ok with this?"
    const val MARK_JUNK = "Mark message(s) as junk"
    const val MARK_NOT_JUNK = "Mark message(s) as not junk"
    const val COMPOSE = "Compose new message"
    const val FETCH = "Fetch new org.knowtiphy.pinkpigmail.messages"
    const val SWITCH_HORIZONTAL = "Switch folder to horizontal layout"
    const val SWITCH_VERTICAL = "Switch folder to vertical layout"
    const val TRUST_SENDER = "Always trust content from this sender"
    const val UNTRUST_SENDER = "No longer trust content from this sender"
    const val FROM = "From"
    const val TO = "To"
    const val CC = "CC"
    const val SUBJECT = "Subject"
    const val ON = "On"
    const val RECEIVED = "Received"
    const val RE = "RE: "
    const val FWD = "Fwd: "
    const val LOAD_REMOTE_CONTENT = "Load remote content"
    const val NO_MESSAGE_SELECTED = "No message selected"
    const val NO_MAIL_IN_THIS_FOLDER = "No mail in this folder"
    const val APPLICATION_ERROR = "Application Error"
    const val APPLICATION_ERROR_HAS_OCCURED = "An application error has occured"
    const val STACKTRACE = "Stack trace"
    const val TODAY = "Today"
    const val YESTERDAY = "Yesterday"
    const val SHUTTING_DOWN = "Shtutting Down"
    const val CONFIGURE_ACCOUNT = "Configure Account"
    const val SYNCHING = "Synching"
    const val SAVE = "Save"
    const val ATTACH_FILE = "Attach file"
    const val CLOSING = "Closing"
    const val SAVE_ATTACHMENT = "Save attachment"
    const val SAVE_ALL_ATTACHMENTS = "Save all attachments"
    const val OPEN_ATTACHMENT = "Open attachment"
    const val REMOVE_ATTACHMENT = "Remove attachment"
    const val REMOVE_ALL_ATTACHMENTS = "Remove all attachments"
    const val ADD_ATTACHMENT = "Add attachment"
    const val OUTBOX = "OUTBOX"
}